sudo: false
language: bash
os: linux
dist: trusty

cache:
  directories:
    - $HOME/astyle

matrix:
  include:
    - env:
      - BUILD_TYPE=build
    - env:
      - BUILD_TYPE=platformio
    - env:
      - BUILD_TYPE=docs
    - env:
      - BUILD_TYPE=package
    - env:
      - BUILD_TYPE=host_tests
    - env:
      - BUILD_TYPE=style_check

install:
  - >
      [ "$BUILD_TYPE" = "docs" ] && {
        pip install --user -r doc/requirements.txt;
      } || true
  - >
      [ "$BUILD_TYPE" = "style_check" ] && {
        [ -f $HOME/astyle/build/gcc/bin/astyle ] || {
          wget -O astyle_3.1_linux.tar.gz https://sourceforge.net/projects/astyle/files/astyle/astyle%203.1/astyle_3.1_linux.tar.gz/download;
          tar -xf astyle_3.1_linux.tar.gz -C $HOME;
          make -C $HOME/astyle/build/gcc;
        }
        make -C $HOME/astyle/build/gcc prefix=$HOME install;
      } || true

script:
  - $TRAVIS_BUILD_DIR/tests/common.sh

deploy:
  provider: releases
  prerelease: true
  skip_cleanup: true
  api_key:
    #secure: A4FBmqyhlzy33oPeZVolg2Q/A3ZcJ3WnRQqQJ3NAPy+qGM5xcboOYtwcLL9vKaHZGfUB7lUP9QVZFGou1Wrmo9DnPvAoe3+XvCaDRGzVMxeIpu7UStbBD4Knbh98tlbMvZCXYRlT4VcusI9bMLK6UWw4sMdPislBh2FEfglTiag=
    secure: 64YKeiVtIlTICiX93MNnQdoMaDz1pLKLhY56H/bbtYGUd317R18jj/4A3S73674Zvxusps0ut1YLcTrsjX9HR0cRiOpSer6lp2BK3CHBHt4thHOwxXGiT7UQ7r2E1iYsmkC8BHgs8YFRD2ucpvEbNWUnk3qxJiT0QxCL831z7FuoB66IRJqQVAV4t9J/K4jDpHF95J4TLy7JmtuNkumh7DMYGYueg34cuAoYjhnVap9oGk+QkjhtC2wnkS/hzn5Vv0xsbciZ3nXDU1gZT72FiqZfZYaOHRH8jBCo+kqsvvj4t9q0YcHGY4E/2Jpr8D0l6LJ49J/31aaHndJbX5u/IRKeoc8pHoxrZHCQvb15jJTleVI2o6OzMSc6hTLvYHR+o4xuZn3Dp+1fCeeHKKQoGyt5iPAeWBQ28g9M7hO/Xl94CIDv64cNMnhnhG05MVF7JGd1H0lywIg/fOrTpKd8GYrKreYLMcuG57LhPF3SLoT2IShsnjkFcmtJDaCsF5/cVhBb76O7utwnStiCvBycjF5lTgnaoBc+1EMD5AD9D4KdviRhL8gAwW6PoAPunsfyiMYaE2fkTWmoCRT9zgWqoOXqRLUixIjWPx5l1O1vhx4P6kIjadCufDf3QMEsr58HC7g2qD0kmb0oxQyhJ8XIYvWFnCU4txA3pPiRR/eDXN0=
  file_glob: true
  file:
    - package/versions/$TRAVIS_TAG/esp8266-$TRAVIS_TAG.zip
    - package/versions/$TRAVIS_TAG/package_esp8266com_index.json
  on:
    #repo: esp8266/Arduino
    tags: true
    condition: "$BUILD_TYPE = package"

notifications:
  email:
    on_success: change
    on_failure: change
#  webhooks:
#    urls:
#      - secure: "dnSY+KA7NK+KD+Z71copmANDUsyVePrZ0iXvXxmqMEQv+lp3j2Z87G5pHn7j0WNcNZrejJqOdbElJ9Q4QESRaAYxTR7cA6ameJeEKHiFJrQtN/4abvoXb9E1CxpL8aNON/xgnqCk+fycOK3nbWWXlJBodzBm7KN64vrcHO7et+M="
#    on_success: change  # options: [always|never|change] default: always
#    on_failure: always  # options: [always|never|change] default: always
#    on_start: false     # default: false
